// Builds the DEBUG-only screenshot fixture (HBPreviewData.swift) by running a realistic month through the real worker and capturing /api/nest.
// It only exists so CI can take simulator screenshots of the native screens without a login; it is compiled out of Release builds.
import { writeFileSync } from "node:fs";
const BASE = process.env.HB_BASE || "http://localhost:8788", ORIGIN = new URL(BASE).origin;
let cookie = "";
async function call(path, method = "GET", body) {
  const h = { accept: "application/json", origin: ORIGIN }; if (cookie) h.cookie = cookie;
  if (body !== undefined || method !== "GET") { h["content-type"] = "application/json"; }
  const r = await fetch(BASE + path, { method, headers: h, body: body === undefined && method === "GET" ? undefined : JSON.stringify(body ?? {}) });
  const sc = r.headers.get("set-cookie"); if (sc) cookie = sc.split(",").map((c) => c.split(";")[0].trim()).filter((c) => c.startsWith("__Host-hb=")).join("; ") || cookie;
  let j = null; try { j = await r.json(); } catch {} return { status: r.status, json: j };
}
const MONTH = "2026-09", d = (n) => `${MONTH}-${String(n).padStart(2, "0")}`;
const day = (n) => new Date(Date.UTC(2026, 9, n)).toISOString().slice(0, 10);
await call("/api/signup", "POST", { name: "Sam", username: "pv" + Date.now() % 1e7, password: "Passw0rd!xyzzy" });
await call("/api/nests", "POST", { name: "Our Hive", kind: "solo" });
await call("/api/setup/done", "POST", {});
const me = (await call("/api/me")).json.user.id;
const add = (type, amount, label, date, category) => call("/api/entries", "POST", { type, amount, label, date, member_id: me, shared: false, private: false, ...(category ? { category } : {}) });
await add("income", 2540, "Paycheck", d(1));
// categories sum to 1897.82: food 531.24, shopping 417.11, bills 341.12, entertainment 227.38, other 380.97
const spend = [
  ["food", [["Chipotle", 18.4, 2], ["Groceries run", 96.2, 4], ["Dinner out", 62.5, 6], ["Coffee beans", 24.8, 9], ["Sushi night", 88.0, 12], ["Brunch", 41.3, 15], ["Takeout", 33.9, 18], ["Farmers market", 57.6, 21], ["Pizza", 29.4, 24], ["Bakery", 79.14, 27]]],
  ["groc", [["Target", 120.5, 3], ["Clothes", 86.0, 7], ["Home goods", 74.11, 11], ["Gifts", 52.0, 16], ["Online order", 45.5, 19], ["Pharmacy run", 39.0, 25]]],
  ["bills", [["Electric", 96.12, 5], ["Internet", 65.0, 10], ["Phone", 80.0, 14], ["Water", 40.0, 20], ["Insurance", 60.0, 28]]],
  ["fun", [["Movies", 38.38, 8], ["Concert", 120.0, 13], ["Games", 69.0, 22]]],
  ["other", [["Haircut", 45.0, 4], ["Donation", 30.0, 9], ["Car wash", 25.97, 17], ["Misc", 140.0, 23], ["Parking", 40.0, 26], ["Repairs", 100.0, 29]]],
];
for (const [cat, rows] of spend) for (const [label, amt, dayN] of rows) await add("expense", amt, label, d(dayN), cat);
await call("/api/recurring", "POST", { type: "expense", amount: 15.99, label: "Netflix", freq: "monthly", date: day(5), member_id: me, shared: false, category: "subs" });
await call("/api/recurring", "POST", { type: "expense", amount: 9.99, label: "Discord Nitro", freq: "monthly", date: day(8), member_id: me, shared: false, category: "subs" });
await call("/api/recurring", "POST", { type: "expense", amount: 850, label: "Rent", freq: "monthly", date: "2026-11-01", member_id: me, shared: false, category: "home" });
const snap = (await call("/api/nest?month=" + MONTH)).json;
snap.members.forEach((m) => { m.streak = 12; });
snap.inbox = { unread: 1 };
// last month (for the chart and "18% lower" card): the same kind of month, totalling 2314.00
const prevDays = [[2, 61.4], [3, 118.2], [5, 74.9], [6, 142.0], [8, 53.5], [9, 96.3], [11, 188.8], [12, 70.2], [14, 131.6], [15, 92.4], [17, 160.9], [18, 58.7], [20, 126.5], [21, 83.1], [23, 149.3], [24, 66.8], [26, 172.0], [27, 90.4], [29, 120.0]];
const prevSum = prevDays.reduce((a, [, v]) => a + v, 0);
prevDays[prevDays.length - 1][1] = Math.round((prevDays[prevDays.length - 1][1] + (2314 - prevSum)) * 100) / 100;
const spent = snap.entries.filter((e) => e.type === "expense").reduce((a, e) => a + e.amount_cents, 0);
console.log("income", snap.entries.filter((e) => e.type === "income").reduce((a, e) => a + e.amount_cents, 0) / 100, "spent", spent / 100);
const swift = `#if DEBUG
// GENERATED by ios-app/tests/make-preview.mjs. Debug builds only (CI screenshots); never compiled into Release/TestFlight builds.
enum HBPreviewData {
    static let month = "${MONTH}"
    static let previousDaily: [Int: Double] = [${prevDays.map(([d, v]) => `${d}: ${v}`).join(", ")}]
    static let json = #"""
${JSON.stringify(snap)}
"""#
}
#endif
`;
writeFileSync(new URL("../ios/App/HoneybunSwiftUI/Core/HBPreviewData.swift", import.meta.url), swift);
