// Generates the native app's Help FAQ and "What's new" list from the website's own source (public/app.js HELP, public/lp.js LOG/TAGS),
// so the iPhone app can't drift from the website. Run `node scripts/gen-content.mjs` after changing either; CI runs it with --check.
import { readFileSync, writeFileSync } from "node:fs";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const out = join(root, "ios-app/ios/App/HoneybunSwiftUI/Core/HBContent.swift");

// the text of the [...] or {...} that starts at `open`, skipping over strings
function balanced(src, open) {
  const pairs = { "[": "]", "{": "}" };
  const close = pairs[src[open]];
  let depth = 0, i = open;
  for (; i < src.length; i++) {
    const c = src[i];
    if (c === '"' || c === "'" || c === "`") { const q = c; for (i++; i < src.length && src[i] !== q; i++) if (src[i] === "\\") i++; continue; }
    if (c === src[open]) depth++;
    else if (c === close && --depth === 0) return src.slice(open, i + 1);
  }
  throw new Error("unbalanced");
}
function grab(file, marker) {
  const src = readFileSync(join(root, file), "utf8");
  const at = src.indexOf(marker);
  if (at < 0) throw new Error(marker + " not found in " + file);
  const start = src.indexOf(marker[marker.length - 1], at + marker.length - 1);
  return vm.runInNewContext("(" + balanced(src, start) + ")");
}

const help = grab("public/app.js", "const HELP = [");
const log = grab("public/lp.js", "var LOG = [");
const tags = grab("public/lp.js", "var TAGS = {");
const json = (v) => JSON.stringify(v, null, 1);
const swift = `// GENERATED by ios-app/scripts/gen-content.mjs from public/app.js (HELP) and public/lp.js (LOG, TAGS). Do not edit by hand:
// change the website's lists and run \`node ios-app/scripts/gen-content.mjs\` (CI checks they match).
enum HBContent {
    static let helpJSON = #"""
${json(help)}
"""#
    static let updatesJSON = #"""
${json(log)}
"""#
    static let tagsJSON = #"""
${json(tags)}
"""#
}
`;
if (process.argv.includes("--check")) {
  let cur = ""; try { cur = readFileSync(out, "utf8"); } catch {}
  if (cur !== swift) { console.error("HBContent.swift is out of date. Run: node ios-app/scripts/gen-content.mjs"); process.exit(1); }
  console.log("HBContent.swift matches the website (" + help.length + " help topics, " + log.length + " releases)");
} else {
  writeFileSync(out, swift);
  console.log("wrote HBContent.swift: " + help.length + " help topics, " + log.length + " releases");
}
