// GENERATED by ios-app/scripts/gen-content.mjs from public/app.js (HELP) and public/lp.js (LOG, TAGS). Do not edit by hand:
// change the website's lists and run `node ios-app/scripts/gen-content.mjs` (CI checks they match).
enum HBContent {
    static let helpJSON = #"""
[
 {
  "t": "Getting started",
  "d": "Budgets, bills, goals and household setup",
  "q": [
   [
    "How do I invite my partner or family?",
    "Go to Together and share your invite link or code. When they sign up with it, you'll share one budget."
   ],
   [
    "How do referral gift cards work?",
    "Open Invite friends from Home or Settings and share your link. A friend counts once they confirm their email, log spending on 4 different days, and are still using Honeybun a week after signing up. Every 10 friends who count earns you a $10 gift card by email. Ask Bun in your inbox anytime to see who signed up."
   ],
   [
    "How do bills and paydays work?",
    "Add them once in Plan, or tap + and choose how often it repeats. Home shows what's due before your next payday, and Bun reminds you."
   ],
   [
    "How do monthly budgets work?",
    "In Plan, tap Edit next to Budget and set a limit for any category. Bun gives you a heads-up at 80%."
   ]
  ]
 },
 {
  "t": "Adding transactions",
  "d": "Spending, income, splits and repeats",
  "q": [
   [
    "What are the one-tap buttons on the Add screen?",
    "Your five most common expenses from the last 90 days. Tap one and it's logged right away with the same amount, category and split as last time. You can edit it after like any entry."
   ],
   [
    "Can Apple Pay log purchases automatically?",
    "Yes. In Settings, open Apple Pay auto-logging and make a key. Then an iPhone Shortcut automation runs every time you tap to pay and sends the amount and store to Honeybun. It picks the category from the store name and remembers how you split each store. No bank connection needed."
   ],
   [
    "How do I split an expense?",
    "When adding an expense, tap Split it, then choose Evenly, By %, or Set amount owed."
   ],
   [
    "Can I keep something private?",
    "Yes. For your own personal spending or income, turn on Only I can see this."
   ],
   [
    "How do I edit or delete something?",
    "Tap any entry to edit it. Tap × to delete it, and you can Undo right after."
   ]
  ]
 },
 {
  "t": "Together",
  "d": "Shared expenses, balances and settling up",
  "q": [
   [
    "How does Settle up work?",
    "Honeybun adds up every split expense. When one of you pays the other back, tap Settle up so the balance resets."
   ],
   [
    "Can I use Honeybun on my own?",
    "Yes. Pick Just me when you start, or change the budget type anytime in Settings."
   ]
  ]
 },
 {
  "t": "Stats & exports",
  "d": "Monthly insights, badges and CSV exports",
  "q": [
   [
    "How do carrots and streaks work?",
    "You earn carrots when you log spending, pay bills, save, or settle up. Log one thing each day to keep your hop streak and level up your bunny."
   ],
   [
    "Can I export my data?",
    "Yes. In Settings, under Data, you can download a spreadsheet (CSV) or a full copy of your data."
   ]
  ]
 }
]
"""#
    static let updatesJSON = #"""
[
 {
  "v": "3.0",
  "date": "2026-10-04",
  "name": "Honeybun 3.0",
  "items": [
   {
    "t": "Honeybun for iPhone is here",
    "d": "A real iPhone app. It opens straight to your budget with a native tab bar, pull to refresh, swipe back, a Face ID lock, and small taps when you add or delete. The app icon even puts on a witch hat for Halloween.",
    "tags": [
     "new"
    ],
    "icon": "landing"
   },
   {
    "t": "Notifications that make a sound",
    "d": "Your phone now gets a push notification, with a sound, when your partner adds something to your joint account, when a bill is due, and when Bun has news. It asks once when you open the app.",
    "tags": [
     "new"
    ],
    "icon": "bell"
   },
   {
    "t": "Swipe, pull and tap",
    "d": "Swipe a spending row right to edit it or left to delete it, pull down to refresh, and the Add screen opens on the category you used last.",
    "tags": [
     "new"
    ],
    "icon": "tap"
   },
   {
    "t": "Join with a code, made easy",
    "d": "On the start screen the invite code box now comes first. If you already made your own budget, Settings has Join with a code, which moves you into your partner's budget.",
    "tags": [
     "improved"
    ],
    "icon": "key"
   },
   {
    "t": "Joint accounts keep it all in one pot",
    "d": "Entries can't be private on a joint account any more, so your balance, forecast and carry-over always include everything. Your partner hears about it when you add something.",
    "tags": [
     "improved"
    ],
    "icon": "budget"
   },
   {
    "t": "The app updates itself",
    "d": "No more Refresh button. When a new version is out, the iPhone app quietly updates in the background the next time you open it.",
    "tags": [
     "improved"
    ],
    "icon": "landing"
   },
   {
    "t": "A cleaner iPhone app",
    "d": "No scroll bar down the side, no install steps or theme settings you don't need, and your streak, level and gift card now live in Bun's inbox.",
    "tags": [
     "design"
    ],
    "icon": "landing"
   },
   {
    "t": "A smarter forecast",
    "d": "The month-end forecast waits for a week of spending, counts a big one-off purchase once, and shows how it got its number: what is left now, paychecks, bills and everyday spending.",
    "tags": [
     "improved"
    ],
    "icon": "budget"
   },
   {
    "t": "Bun's tips come as notifications",
    "d": "Bun's tip card and the status line on Home are gone. Instead, Bun sends you a helpful tip as a notification every few days, with your own numbers when there's something worth pointing out.",
    "tags": [
     "new",
     "design"
    ],
    "icon": "bell"
   },
   {
    "t": "New buddies",
    "d": "Pick from 12 new buddies: Bun in a honey pot as a cowboy, witch, ghost, angel, devil, frog, dinosaur and more. Your current buddy turns into its new look automatically. The color picker is gone, since the pictures bring their own look.",
    "tags": [
     "new",
     "design"
    ],
    "icon": "sun"
   },
   {
    "t": "Halloween Honeybun fits every phone",
    "d": "Halloween mode now adapts to any screen size and the iPhone safe areas. Coming up shows your real bills and payments and you can edit them, goals get fitting icons, and the shopping list is plain and fully editable.",
    "tags": [
     "new",
     "fix"
    ],
    "icon": "sun"
   },
   {
    "t": "A new Honeybun icon",
    "d": "Bun is now peeking out of a honey pot, on the website, the iPhone app and the Windows app. During Halloween, Bun wears a witch hat in a spooky cauldron.",
    "tags": [
     "new",
     "design"
    ],
    "icon": "sun"
   },
   {
    "t": "A homepage built around the app",
    "d": "The homepage now leads with the App Store and real screenshots of the app. The Windows app is still there for anyone who has it.",
    "tags": [
     "design"
    ],
    "icon": "landing"
   },
   {
    "t": "Widgets and Siri can sign in",
    "d": "The home-screen widget and Siri shortcuts now share your sign-in with the app, so they can show what is left.",
    "tags": [
     "fixed"
    ],
    "icon": "bug"
   },
   {
    "t": "Plan calendar fixed",
    "d": "On phones the day numbers were drawn above their boxes. They sit where they belong now.",
    "tags": [
     "fixed"
    ],
    "icon": "bug"
   }
  ]
 },
 {
  "v": "2.0",
  "date": "2026-09-30",
  "name": "Honeybun 2.0",
  "items": [
   {
    "t": "Honeybun goes spooky",
    "d": "A glowing moon, flapping bats, dangling spiders, cobwebs, drifting fog and a little graveyard now light up the homepage and the app, with warm orange buttons and Bun in a witch hat. It's on from Sept 29 through October and switches itself off after.",
    "tags": [
     "new",
     "design"
    ],
    "icon": "sun"
   },
   {
    "t": "Honeybun for Windows",
    "d": "Download Honeybun for Windows and keep it on your taskbar, with the same account as your phone and the web. It shows a red dot when Bun has something new, and Bun can wait in your tray with no window open.",
    "tags": [
     "new"
    ],
    "icon": "landing"
   },
   {
    "t": "It updates itself",
    "d": "The Windows app checks for a newer version when it opens and every few hours, shows the progress under Bun, then installs it and reopens. There's also a Check for updates button in the side menu.",
    "tags": [
     "new"
    ],
    "icon": "landing"
   },
   {
    "t": "A brand new homepage",
    "d": "A fresh look with a hopping Bun, live mini demos of every feature, a hop calendar preview, and a Download section for Windows and phones. You can also install Honeybun from Chrome or Edge in one click.",
    "tags": [
     "new",
     "design"
    ],
    "icon": "landing"
   },
   {
    "t": "Bun's tip of the day",
    "d": "A new card on Home with a tip from Bun, based on your month: a budget running low, habits that add up, subscriptions, no-spend days, savings goals and your streak.",
    "tags": [
     "new"
    ],
    "icon": "bell"
   },
   {
    "t": "Subscriptions in Plan",
    "d": "Bills & paydays has a Subscriptions tab with every subscription, its next charge, what it costs you a month and a year, and a button to add one.",
    "tags": [
     "new"
    ],
    "icon": "budget"
   },
   {
    "t": "Honeybun for iPhone",
    "d": "A native iPhone app with a Face ID lock, home-screen and lock-screen widgets that show what is left this month, real push notifications, and Siri shortcuts like Hey Siri, log an expense in Honeybun.",
    "tags": [
     "new"
    ],
    "icon": "landing"
   },
   {
    "t": "Easier sign-up",
    "d": "Sign up with just a username (no email needed), or with Face ID or a passkey. Without an email you get a recovery code to save, so you can still reset your password. Your existing email login works exactly as before.",
    "tags": [
     "new"
    ],
    "icon": "landing"
   },
   {
    "t": "Month-end forecast",
    "d": "A card in Stats (and a line on Home) guesses where the month is heading, with a chart, a what-if for saving a little each day, and how you compare with last month.",
    "tags": [
     "new"
    ],
    "icon": "budget"
   },
   {
    "t": "Your own categories",
    "d": "Make categories with your own name and emoji, like Dog treats. Add one from the Add screen or manage them under Budget in Plan, and they work in budgets, stats and alerts.",
    "tags": [
     "new"
    ],
    "icon": "budget"
   },
   {
    "t": "Shared shopping list",
    "d": "Add what you need, tick it off in the store and see your partner's changes within seconds. When you're done, log what you paid as groceries in one tap, split like any shared expense. Find it on Together, or on Home when the list has something on it.",
    "tags": [
     "new"
    ],
    "icon": "budget"
   },
   {
    "t": "Carry over last month's balance",
    "d": "On the first of every month Honeybun asks if you want to carry last month's leftover (or shortfall) into the new month, by notification and when you open Home. Say yes and it shows on Home as Carried over from last month and counts in your balance. Your partner sees the same answer. You can change your mind with Change on Home, and pick Always carry or Start fresh in Settings so it stops asking.",
    "tags": [
     "new"
    ],
    "icon": "budget"
   },
   {
    "t": "Bun gets sleepy",
    "d": "If nothing has been logged for 3 days, Bun looks sleepy on Home and asks you to log something. Log anything and Bun perks right up.",
    "tags": [
     "new"
    ],
    "icon": "bell"
   },
   {
    "t": "Heads-up alerts",
    "d": "A Heads up from Bun card on Home warns you when a category budget is at 80% or over, with what you can spend per day for the rest of the month, and tells you when a subscription's price goes up or down.",
    "tags": [
     "new"
    ],
    "icon": "bell"
   },
   {
    "t": "Joint accounts",
    "d": "Couples who share one bank account can turn on Joint account in Settings and everything adds up together: Together shows one pot with what came in, what was spent and what is left, nobody owes anybody, and expenses are not split.",
    "tags": [
     "new"
    ],
    "icon": "landing"
   },
   {
    "t": "Fair share for couples",
    "d": "A new tab for partners: who brought in how much, who has spent how much, and a little brainstorm tool to try splitting shared costs 50/50, by income, or with your own slider.",
    "tags": [
     "new"
    ],
    "icon": "landing"
   },
   {
    "t": "Lighter on your computer",
    "d": "The Windows app now pauses its animations and refreshing whenever the window is in the background or hidden in the tray, resizing is smoother, and slower computers switch to a lite look on their own.",
    "tags": [
     "improved"
    ],
    "icon": "landing"
   },
   {
    "t": "Tidier Home and Plan",
    "d": "Coming up, Debts, Bills and Subscriptions show a page at a time, so nothing needs to scroll on desktop.",
    "tags": [
     "improved"
    ],
    "icon": "budget"
   },
   {
    "t": "Fixes",
    "d": "Email reminders stay on after you confirm your email, the homepage cards no longer overlap on phones, and Bun skips habit tips about the catch-all Other category.",
    "tags": [
     "fixed"
    ],
    "icon": "bell"
   }
  ]
 },
 {
  "v": "1.7",
  "date": "2026-09-29",
  "name": "New Stats and one-screen desktop",
  "items": [
   {
    "t": "Hop calendar",
    "d": "Stats now opens on a calendar of your month. Bigger dots mean bigger spending days, and paw prints mark days you spent nothing. See your no-spend days, calmest week, and biggest day at a glance.",
    "tags": [
     "new",
     "design"
    ],
    "icon": "landing"
   },
   {
    "t": "Where it went, by month or year",
    "d": "One card with a Month and Year switch, plus a one-line 50/30/20 check. Your year chart and badges open in their own windows.",
    "tags": [
     "improved"
    ],
    "icon": "landing"
   },
   {
    "t": "Desktop fits your screen, top to bottom",
    "d": "Every tab now fits on one screen without scrolling, from small laptops to 1920×1080 monitors. Settings sits in three tidy columns and Plan in three.",
    "tags": [
     "improved",
     "design"
    ],
    "icon": "landing"
   }
  ]
 },
 {
  "v": "1.6",
  "date": "2026-09-28",
  "name": "Referral rewards",
  "items": [
   {
    "t": "Invite friends, earn gift cards",
    "d": "Share your personal link. For every 10 friends who use Honeybun for a week, you get a $10 gift card. Find it on Home, in Settings, or in the sidebar.",
    "tags": [
     "new"
    ],
    "icon": "bell"
   },
   {
    "t": "Ask Bun about your referrals",
    "d": "Tap Referrals in Bun's inbox and Bun tells you who signed up, who counts, and how close you are to your next gift card.",
    "tags": [
     "new"
    ],
    "icon": "bell"
   },
   {
    "t": "Pages for your monthly list",
    "d": "Everything this month and search results show 8 at a time with page buttons underneath, so the Together screen stays short.",
    "tags": [
     "improved"
    ],
    "icon": "landing"
   }
  ]
 },
 {
  "v": "1.5",
  "date": "2026-09-28",
  "name": "Desktop polish and fit to screen",
  "items": [
   {
    "t": "Desktop fits your screen",
    "d": "The wide layout now scales to your monitor, so a big screen sees the same composition, just larger. Sidebar gets Bun's inbox, Help, Settings, and your household at the bottom.",
    "tags": [
     "improved",
     "design"
    ],
    "icon": "landing"
   },
   {
    "t": "Home and Stats rearranged on desktop",
    "d": "Home shows Bills, Bun's note, and Honey jars in the right column with a fourth Month left stat. Stats puts your level and numbers in one row, with Where it went beside the year chart.",
    "tags": [
     "design"
    ],
    "icon": "landing"
   },
   {
    "t": "Latest fills the Home column on desktop",
    "d": "Home shows ten recent entries on desktop, five per column, so the space under the list is used.",
    "tags": [
     "improved"
    ],
    "icon": "landing"
   },
   {
    "t": "Plan matches the design on desktop",
    "d": "Compact calendar with a legend, a dashed Add a bill button, dashed New jar tile, and one-line empty states. Calendar numbers sit inside their cells again.",
    "tags": [
     "fixed",
     "design"
    ],
    "icon": "budget"
   }
  ]
 },
 {
  "v": "1.4",
  "date": "2026-09-28",
  "name": "A real desktop layout",
  "items": [
   {
    "t": "Desktop layout",
    "d": "On laptops and desktops the app now has a left sidebar instead of the bottom bar, and every screen uses a proper multi-column layout: Plan shows budget, calendar, and bills side by side, Stats puts the charts next to your progress, Together gives the balance its own column. Phones are unchanged.",
    "tags": [
     "design",
     "improved"
    ],
    "icon": "landing"
   },
   {
    "t": "Updates grouped by release",
    "d": "This page now folds each release into one row you can open, so it stays short as the list grows.",
    "tags": [
     "improved"
    ],
    "icon": "landing"
   }
  ]
 },
 {
  "v": "1.3",
  "date": "2026-09-28",
  "name": "Passkeys, push, and a new front door",
  "items": [
   {
    "t": "New landing page",
    "d": "A fresh front door in the app's own colors: a live money card with Bun's ears, a split slider you can drag, and the tap-to-pay scene. Works in light and dark, in three languages.",
    "tags": [
     "design"
    ],
    "icon": "landing"
   },
   {
    "t": "Updates tab",
    "d": "This page. Everything we ship shows up here, newest first.",
    "tags": [
     "new"
    ],
    "icon": "landing"
   },
   {
    "t": "Bun's inbox opened to an error",
    "d": "Opening the inbox showed \"Something went wrong\" after the budget rollover update. Fixed within the hour.",
    "tags": [
     "fixed"
    ],
    "icon": "bug"
   },
   {
    "t": "Passkeys",
    "d": "Log in with Face ID, Touch ID, or your phone's unlock instead of a password. Add one per device in Settings. Passkeys can't be phished or guessed.",
    "tags": [
     "new",
     "security"
    ],
    "icon": "key"
   },
   {
    "t": "Push notifications",
    "d": "Turn on push in Settings and get a nudge when a bill is due, your streak is about to break, or your partner adds a shared expense. On iPhone, add Honeybun to your Home Screen first.",
    "tags": [
     "new"
    ],
    "icon": "bell"
   },
   {
    "t": "Light, dark, or auto",
    "d": "A new Appearance setting. Auto follows your device. The whole app, including this page, has a proper light palette now.",
    "tags": [
     "new",
     "design"
    ],
    "icon": "sun"
   },
   {
    "t": "Budget rollover",
    "d": "Turn it on in the budgets dialog and whatever you don't spend carries into next month, starting the month you switch it on.",
    "tags": [
     "new"
    ],
    "icon": "budget"
   },
   {
    "t": "Search by amount and date",
    "d": "Tap More next to the search filters to narrow by an amount range or a date range.",
    "tags": [
     "improved"
    ],
    "icon": "search"
   },
   {
    "t": "Undo after adding",
    "d": "Every add, including one-tap repeats, shows an Undo button for a few seconds.",
    "tags": [
     "improved"
    ],
    "icon": "undo"
   },
   {
    "t": "Apple Pay auto-logging",
    "d": "Make a key in Settings and an iPhone Shortcut logs every tap-to-pay purchase for you. Category guessed from the store, split remembered from last time. No bank connection.",
    "tags": [
     "new"
    ],
    "icon": "tap"
   },
   {
    "t": "One-tap repeats",
    "d": "Your five most common expenses sit at the top of the Add screen. Tap one and it's logged with the same amount, category, and split as last time.",
    "tags": [
     "new"
    ],
    "icon": "repeat"
   }
  ]
 }
]
"""#
    static let tagsJSON = #"""
{
 "new": "New",
 "improved": "Improved",
 "fixed": "Fixed",
 "design": "Design",
 "security": "Security"
}
"""#
}
